### ISSUE TITLE
Cannot restore plugin on platform add

### ISSUE THREAD

**Issue by horodnicdragos** [ionic-team/ionic-plugin-deeplinks#138]
Greetings!

I am using ionic-cli 3.19.0 and  I want to add ios platform like this:

`ionic cordova platform add ios
`
I have all my plugins saved in config.xml, here is how this one is stored:

`    <plugin name="ionic-plugin-deeplinks" spec="https://github.com/ionic-team/ionic-plugin-deeplinks">
        <variable name="URL_SCHEME" value="https" />
        <variable name="DEEPLINK_SCHEME" value="https" />
        <variable name="DEEPLINK_HOST" value="something.com" />
        <variable name="ANDROID_PATH_PREFIX" value="/" />
    </plugin>`

The error I get is the following:

`Failed to install 'ionic-plugin-deeplinks':Error: Variable(s) missing: URL_SCHEME, DEEPLINK_HOST
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:362:23
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Error: Variable(s) missing: URL_SCHEME, DEEPLINK_HOST`

Is there any workaround to avoid adding the plugin from CLI and then restoring my config.xml as it was before? It is quite cumbersome doing this over and over again.

Thank you!

**Comment by GreenRover** [comment]
The problem also exist when addint it via package.json "plugins" section

**Comment by chrisweight** [comment]
@horodnicdragos - have you checked your 'plugins/fetch.json` to see if the variables are present in the plugin node there too?

**Comment by royalrex** [comment]
I have the same problem. It used to be okay, but for some reason, now I get this issue too.

@chrisweight I checked the plugins/fetch.json file and the correct variables are there, as well as in package.json and config.xml.

Any suggestions?

**Comment by royalrex** [comment]
Did some further fooling around and found the problem.

I have added my plugins dir to git to speed up build times in my CD system, as it would no longer need to pull all the plugins (takes forever). However, removing plugins dir or ionic-plugin-deeplinks dir, fixes this issue.

Don't know if there is anyway the plugin can be "reinstalled" somehow if it already exists.

**Comment by dhayaljaswantgit** [comment]
You can just use : cordova plugin add ionic-plugin-deeplinks@latest

this will install latest version of plugin and issue will resolved

**Comment by jpike88** [comment]
Took me 5 hours to realise this is so broken fundamentally.

@elylucas can you give some insight?
