### ISSUE TITLE
Can't install ionic deeplinks plugin with Npm 5.6 and Node 9.0.3 in Kali linux

### ISSUE THREAD

**Issue by wadleo** [ionic-team/ionic-plugin-deeplinks#151]
When I run  
ionic cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=cmtvapp --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=chillenmedia.com
Output
> cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=cmtvapp --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=chillenmedia.com --save
(node:13219) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin ionic-plugin-deeplinks via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! Unexpected token < in JSON at position 41405

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-04T14_25_44_954Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:13219) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13219) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And when I run npm install --save @ionic-native/deeplinks
npm ERR! Unexpected token < in JSON at position 41405

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-04T14_27_01_841Z-debug.log

**Comment by chrisweight** [comment]
Ok, I've installed Kali on VirtualBox, along with Node 9.11.2 and npm 5.6.0.

I've started a blank ionic / cordova project

I've used:

```
ionic cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=cmtvapp --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=chillenmedia.com
```

and ` npm install --save @ionic-native/deeplinks`

both have worked without issue.

Can you try updating your Node install, clearing your NPM cache and try again?

**Comment by wadleo** [comment]
Ok, thanks for checking it out, I will give you feedback
